### ISSUE TITLE
Not loading the app UI in the browser

### ISSUE THREAD

**Issue by dove88** [lana-k/sqliteviz#104]
I tried to load index.html from dist.map folder, unfortunately the web browser is not loading the UI of your app, hence can't not view anything from the app.

Kindly advise...

**Comment by lana-k** [comment]
Just in case: the last version of the app is deployed on https://sqliteviz.com/app/#/. So, you can always use the app there or install it from there and use it offline.

But if you want to deploy sqliteviz locally you need a local HTTP server. E.g. you can use Python HTTP server module as described on [MDN]( https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server#running_a_simple_local_http_server). After installation of Python just run `python3 -m http.server` in the folder with `index.html`.

>By default, this will run the contents of the directory on a local web server, on port 8000. You can go to this server by going to the URL `localhost:8000` in your web browser.

**Comment by dove88** [comment]
Thank you
