### ISSUE TITLE
Pre-defined databases

### ISSUE THREAD

**Issue by benyn** [lana-k/sqliteviz#108]
Hi Lana,

I just discovered `sqliteviz` and I'm loving it. But is there a way to programmatically load a predefined SQLite database file instead of having to manually drag and drop a `.sqlite` file each time?

I'm running `sqliteviz` locally via a static HTTP server, and I'm looking for a config option similar to [predefined inquiries](https://sqliteviz.com/docs/integrate-predefined-inquiries/). If such an option doesn't exist, could there be a JavaScript function I could call to load a database file?

**Comment by lana-k** [comment]
Hi,

I'm glad that you like it. Currently [this RFE](https://github.com/lana-k/sqliteviz/issues/41) is in progress. When it's finished you will be able to set  the database file url in the query parameters and it will be loaded automatically.

**Comment by lana-k** [comment]
Generating a share link is ready. See https://sqliteviz.com/docs/sharing/
