### ISSUE TITLE
'>>>' should be deleted?

### ISSUE THREAD

**Issue by swuecho** [lana-k/sqliteviz#47]
https://github.com/lana-k/sqliteviz/blob/cc483f4720f8f6b04e94e33765c42bc9a1b4e831/src/views/Main/Editor/Tabs/Tab/Chart/index.vue#L95

**Comment by lana-k** [comment]
@swuecho No, it's a [deep selector][1]:
>If you want a selector in scoped styles to be "deep", i.e. affecting child components, you can use the >>> combinator

I use it to change the styles of a third-party child component.

[1]: https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors
