### ISSUE TITLE
[RFE] Clipboard interactions

### ISSUE THREAD

**Issue by saaj** [lana-k/sqliteviz#50]
As a user of sqliteviz,
In order to speed up introp with other local software,
I want to be able to copy and paste into/from sqliteviz.

It's mostly about tiny data volumes and a small convenience of interaction with sqliteviz. For instance you copy something from a spreadsheet, instead of moving it to another sheet, saving as CSV and drag'n'dropping to sqliteviz. Or export PNG with a chart to share it in a chat app.

What on the surface:
1. Past CSV (table structure you copy from Libre Office Calc, Google Sheets, etc) for import (probably in a text area because JS isn't allowed to examine the clipboard on it's own)
2. Copy result set as a CSV (table structure that the spreadsheet editors recognise; saving as a file also makes sense by the way)
3. Copy PNG from Plotly

**Comment by lana-k** [comment]
Pasting CSV is split to https://github.com/lana-k/sqliteviz/issues/82
