### ISSUE TITLE
[RFE] Display errors from the visualisation component in the UI

### ISSUE THREAD

**Issue by saaj** [lana-k/sqliteviz#55]
As a user of sqliteviz,
In order to understand if my visualisation config is wrong,
I want sqliteviz to display the error from the visualisation (i.e. Plotly at the moment).

- Example 1
  ```
   WITH t("labels", "parents", "values") AS (
     VALUES 
       ('foo', 'bar', 1),
       ('foo', 'baz', 2),
       ('baz', 'qux', 3)  
   )
   SELECT * FROM t
   ```
   Try to plot a treemap. It fails with this error in the console and nothing in the UI.
   ```
   console.trace() WARN: Multiple implied roots, cannot build treemap hierarchy of trace 0. These roots include: bar, qux
   ```

- Example 2
  ```
   WITH t("labels", "parents", "values") AS (
     VALUES 
       ('bar', NULL, 1),
       ('foo2', 'baz', 2),
       ('foo3', 'bar', 3)  
   )
   SELECT * FROM t
   ```
   ```
   console.trace() WARN: Failed to build treemap hierarchy of trace 0. Error: missing: baz
   ```
- and other errors for treemap. It's probably the case also for other chart types.

**Comment by lana-k** [comment]
Plotly warnings and errors now will be displayed as notifications using `notifyOnLogging = 1` plotly config option.
![image](https://user-images.githubusercontent.com/24638357/146678868-6fd6f144-458d-49f0-bf2e-aec6fe4b9e77.png)

**Comment by lana-k** [comment]
There are cases when plotly doesn't report about wrong data: https://github.com/plotly/plotly.js/issues/6064
