### ISSUE TITLE
If CSV has ISO time as column resulting SQL Table is empty

### ISSUE THREAD

**Issue by ZlydeTJ** [lana-k/sqliteviz#64]
Hi,

If I import a CSV with time data in a column I get "No rows selected" after running a query. Using it without the time data works perfectly fine.

#### Import CSV:
```
"id","createdOn"
"60dc8bd397491cb72be381e3","2021-06-30T15:20:51.469Z"
"60dc83c297491cb72be381af","2021-06-30T14:46:26.326Z"
"60dc813997491cb72be381a2","2021-06-30T14:35:37.010Z"
"60dc813797491cb72be381a1","2021-06-30T14:35:35.629Z"
"60dc7b5097491cb72be38165","2021-06-30T14:10:24.717Z"
```

#### Run query (select all rows from the imported CSV)
**Actual result**
No rows selected

**Expected result**
5 rows selected

**Comment by lana-k** [comment]
Hi @ZlydeTJ ,

Thank you for letting me know about the issue. Indeed, there is an error because CSV parser returns date as `Date` object and it can not be inserted into the database because SQLite doesn't support `Date` type. I'll fix it as soon as possible.

**Comment by ZlydeTJ** [comment]
Hi @lana-k,

Thank you for fixing the Issue this fast! Working with sqliteviz is very enjoyable.
