### ISSUE TITLE
Wiki improvement pull request

### ISSUE THREAD

**Issue by saaj** [lana-k/sqliteviz#72]
Because GitHub doesn't support pull requests for its wiki repos, this is a request for manual pull from my fork's wiki repo. Changes in https://github.com/saaj/sqliteviz/wiki:

1. Use wiki page names as link targets instead of full URLs
2. Add table of contents when the page has more than one section
3. Merge pages about inquiries
4. Wrap lines by 80 characters
5. Add a section on pivot tables in SQL
6. Minor spelling, typography and so on

**Comment by lana-k** [comment]
>You can render any visualisation as an image by clicking 

It sounds confusing: the visualisation is already rendered. Would be better use `save` or `download`.

**Comment by saaj** [comment]
Done in 2797507b.

**Comment by lana-k** [comment]
pushed
