### ISSUE TITLE
Filtered values influence axis range if Split transformation is active

### ISSUE THREAD

**Issue by oliver** [lana-k/sqliteviz#76]
If I have a Filter transformation and also a Split transformation, the filtered (ie. invisible) values will still influence the automatic range of the graph axis. Looks like this doesn't affect all graph types, though (it happens with Scatter graphs, but apparently not with Bar graphs).

Here's an example:

- load [test2.csv](https://github.com/lana-k/sqliteviz/files/6982744/test2.csv)
- import Inquiry from [graph-range-with-filtered-split-values.json.gz](https://github.com/lana-k/sqliteviz/files/6982747/graph-range-with-filtered-split-values.json.gz)
- run the query and open the graph view
- **problem:** although only two points are visible, the graph extends to the left and bottom to also include the hidden point
- but if I disable the Split transformation, the axis range will change to only include the visible points

Not sure which of these behaviours is "correct". Personally I'd prefer if hidden points would never influence the axis range.

Tested with  sqliteviz version 0.15.2.

**Comment by lana-k** [comment]
The chart editor is a third-party component [react-chart-editor](https://github.com/plotly/react-chart-editor) based on [plotly.js](https://github.com/plotly/plotly.js). So, you should create that kind of issue there.

**Comment by oliver** [comment]
Thanks! I will try to report it for react-chart-editor or plotly.js. I guess you can close the issue here (but please don't delete it, or I'll have to recreate the how-to-repeat steps :)
