### ISSUE TITLE
Position input field of text annotation disappears

### ISSUE THREAD

**Issue by oliver** [lana-k/sqliteviz#77]
It can happen that for a text annotation the horizontal "Position" input field disappears. It is then no longer possible to move the text annotation horizontally at all.

* open [test2.csv](https://github.com/lana-k/sqliteviz/files/6983203/test2.csv)
* create a new text annotation
  * hide its arrow
  * drag text someplace else in the graph area
  * in text annotation properties, under Horizontal Positioning, change "Relative To" to "Canvas"
    * **problem:** the Position input field is now gone
  * drag text someplace else in the graph area again (only vertical movement is now possible!)
  * in text annotation properties, under Horizontal Positioning, change "Relative To" back to "X1"
    * **problem:** the Position input field for X1-relative position is now gone as well

I think the only way to get the input field back is by saving, closing and loading the inquiry (though this doesn't appear to work in all cases - haven't checked why).

**Comment by lana-k** [comment]
The chart editor is a third-party component [react-chart-editor](https://github.com/plotly/react-chart-editor). So, you should create that kind of issue there.
But I can't reproduce the issue. I switched `Relative To` to `Canvas` and still have `Position` input. I tested in Chromium Version 90.0.4430.72 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit) 
![image](https://user-images.githubusercontent.com/24638357/129457496-c35fe50b-815c-4b39-8557-844aa1a72df0.png)

**Comment by oliver** [comment]
Thanks! Strange that it works on your system. I'll do some more tests and will try to report it for react-chart-editor. I guess you can close the issue here (but please don't delete it, or I'll have to recreate the how-to-repeat steps :)
