### ISSUE TITLE
Export Plotly JSON

### ISSUE THREAD

**Issue by thejeshgn** [lana-k/sqliteviz#89]
So the figure can be embedded as HTML embed easily.

**Comment by lana-k** [comment]
Hi @thejeshgn, you can export the figure into `svg` and embed it easily in HTML. If it doesn't work for you, please, provide more details about what task you are trying to solve.

**Comment by thejeshgn** [comment]
@lana-k  thank you for replying. You are correct I can export and embed the SVG.
 

- I was looking as exporting as HTML and embedding HTML in a page. 
- [Chart Studio](https://chart-studio.plotly.com/) give HTML download. But this HTML download is an HTML page with  plotly.js, a div and a JSON data file which is a representation of the plotjs chart data. 
- So if we if give folks the option of download the chart as JSON. They can easily build this HTML and embed this chart as HTML. There are many advantage of HTML chart like the tool bar.
- In fact the Chart Studio also gives an option to download this JSON data.
- So I was wondering if there is a way to export that JSON data it would great.


![plotly_download_html](https://user-images.githubusercontent.com/76114/146678797-bca58589-0833-439e-8b55-6f055c302f8c.png)

![plotly_view_json](https://user-images.githubusercontent.com/76114/146678808-b5724533-63ca-45ba-9b06-40062c9a55e6.png)

![plotly_download_json](https://user-images.githubusercontent.com/76114/146678815-94b27ea5-6430-43f7-8acb-1756eb3e0edc.png)

![plotly_download_html_content](https://user-images.githubusercontent.com/76114/146678820-ebc3a0c0-9d3d-4569-ae38-9e5519bfcf59.png)


Let me know if you need any other details. I am happy to provide.

**Comment by thejeshgn** [comment]
Seems like the how to implement this is answered [here](https://stackoverflow.com/questions/61427387/how-to-plot-whole-graph-as-json-data-into-ploty-using-react-js).

**Comment by thejeshgn** [comment]
Here is how downloaded HTML embed file looks like

http://bl.ocks.org/thejeshgn/dd0ffa5b5791d2ee553b2a722450c78b



Here is the gist. The `data` is passed as variable to `Plotly.plot(gd, {data: [{"meta` at the bottom.
https://gist.github.com/thejeshgn/dd0ffa5b5791d2ee553b2a722450c78b

**Comment by lana-k** [comment]
So, you want to save plotly panel in order to zoom in/zoom out etc. It's a good idea. Thank you. And it looks like it's possible to implement. I'll add this feature in one of the nearest releases.
