### ISSUE TITLE
Execute queries on existing SQLite file

### ISSUE THREAD

**Issue by ad-si** [lana-k/sqliteviz#96]
Is there a way to put an existing SQLite file and sqliteviz on a server and let sqliteviz execute all queries against that file?

**Comment by lana-k** [comment]
You can put an existing SQLite file in sqliteviz (see [docs](https://sqliteviz.com/docs/basic-usage/#choose-sqlite-database-or-csv-file)) and all queries will be executed against that file.

If it doesn't work for you, please tell me more about what task you are trying to solve.
